version: 2

registries:
  python-artifactory:
    type: "python-index"
    url: "https://jfrogghdemo.jfrog.io/artifactory/api/pypi/db-dependbot-python/simple"
    username: "thavaahariharangit@github.com" 
    password: "${{ secrets.PYTHON_TOKEN }}"

    
updates:
  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: "increase"
    insecure-external-code-execution: allow
    schedule:
      interval: "weekly"
    registries:
      - python-artifactory
